artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1y9ftEl30hdWn61l1JJy5IxOUsp956Zpq/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_foundation_model:
  root_dir: artifacts/prepare_foundation_model
  base_model_path: artifacts/prepare_foundation_model/base_model.h5
  updated_base_model_path: artifacts/prepare_foundation_model/base_model_updated.h5


model_trainer: 
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  